routes/web.php
<?php

use App\Http\Controllers\BrandController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\FrontController;
use App\Http\Controllers\MultipicController;
use App\Http\Controllers\SliderController;
use App\Models\Brand;
use App\Models\User;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/email/verify', function () {
    return view('auth.verify-email');
})->middleware('auth')->name('verification.notice');

Route::get('/', function () {
    $brands = Brand::all();
    return view('home', compact('brands'));
});

//Category Controller

Route::get('all', [CategoryController::class, 'index'])->name('all.category');
Route::post('add', [CategoryController::class, 'store'])->name('store.category');
Route::get('editcate/{id}', [CategoryController::class, 'editcate']);
Route::post('update/{id}', [CategoryController::class, 'update']);
Route::get('softdelete/{id}', [CategoryController::class, 'softdelete']);
Route::get('restore/{id}', [CategoryController::class, 'restore']);
Route::get('pdelete/{id}', [CategoryController::class, 'pdelete']);
//brands

Route::get('add/brand', [BrandController::class, 'index'])->name('brands');
Route::post('store/brand', [BrandController::class, 'store'])->name('store.brand');
Route::get('edit_brand/{id}', [BrandController::class, 'edit_brand']);
Route::post('update/{id}', [BrandController::class, 'update']);
Route::get('delete/{id}', [BrandController::class, 'delete']);

//Multi_pic
Route::get('multipic', [MultipicController::class, 'index'])->name('multipic');
Route::post('store/multipic', [MultipicController::class, 'store'])->name('store.multipic');

//Slider
// Route::get('slider', [SliderController::class, 'index'])->name('home.slider');
// Route::get('add/slider', [SliderController::class, 'create'])->name('add.slider');
// Route::post('store/slider', [SliderController::class, 'store'])->name('store.slider');

Route::resource('sliders', SliderController::class);
Route::get('index', [FrontController::class, 'index']);




//Dashboard
Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {

    $users = User::all();
    // $users = DB::table('users')->get();
    return view('admin.index');
})->name('dashboard');

Route::get('logout', [BrandController::class, 'logout'])->name('logout');

app/Models/Slider.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Slider extends Model
{
    use HasFactory;

    protected $fillable = [
        'id',
        'title',
        'description',
        'image',
    ];


}

app/Http/Controllers/SliderController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\SliderRequest;
use App\Models\Slider;
use Illuminate\Http\Request;

use Illuminate\Support\Carbon;
use Image;


class SliderController extends Controller
{
    public function index()
    {
        $sliders = Slider::latest()->paginate();
        return view('admin.slider.index', compact('sliders'));
    }

    public function create()
    {
        return view('admin.slider.create');
    }

    public function store(SliderRequest $request)
    {

        $image = $request->file('image');
        $name_gen = hexdec(uniqid()) . '.' . $image->getClientOriginalExtension();
        Image::make($image)->resize(1920, 1088)->save('image/slider/' . $name_gen);

        $img = 'image/slider/' . $name_gen;

        $slider = new Slider();
        $slider->title = $request->title;
        $slider->description = $request->description;
        $slider->image = $img;
        $slider->save();

        return Redirect()->route('sliders.index')->with('success', 'Slider Inserted Successfully');
    }
    public function show($id)
    {
        $sliders = Slider::find($id);
        return view('admin.slider.show', compact('sliders'));
    }
    public function edit($id)
    {
        $sliders = Slider::find($id);
        return view('admin.slider.edit', compact('sliders'));
    }

    public function update(Request $request ,$id)
    {
        // dd($request->all());
        $slider_id = $request->id;
        $old_image = $request->old_image;

        $image = $request->file('image');


        if ($image) {
            @unlink($old_image);
            $image = $request->file('image');
            $name_gen = hexdec(uniqid()) . '.' . $image->getClientOriginalExtension();
            Image::make($image)->resize(870, 370)->save('image/slider/' . $name_gen);
            $save_url = 'image/slider/' . $name_gen;

            $slider = Slider::find($id);
            $slider->title = $request->title;
            $slider->description = $request->description;
            $slider->image = $save_url;

            $slider->save();
            return Redirect()->route('sliders.index')->with('success', 'Slider update with Image Successfully');

        } else {
            $slider = Slider::find($id);
            $slider->title = $request->title;
            $slider->description = $request->description;
            $slider->save();

            return Redirect()->route('sliders.index')->with('success', 'Slider update with Image Successfully');
        }


    }
    public function destroy($id)
    {
        $slider = Slider::find($id);
        $old_image = $slider->image;
        unlink($old_image);

        Slider::find($id)->delete();
        return Redirect()->back()->with('success', 'Slider Deleted Successfully');
    }
}

resources/views/admin/slider/create.blade.php
@extends('admin.admin_master')

@section('admin')

    <div class="py-12">
        <div class="container">
            <div class="row">

                <div class="col-md-8">
                    <div class="card">
                        <div class="card-header">
                            Add Slider
                        </div>
                        <div class="card-body">
                            <form action="{{ route('sliders.store') }}" method="POST" enctype="multipart/form-data">
                                @csrf

                                <div class="mb-3">
                                  <label for="exampleInputEmail1" class="form-label">Title</label>
                                  <input type="text" class="form-control" name="title">
                                  @error('title')
                                  <span class="text-danger">{{ $message }}</span>
                                  @enderror
                                </div>

                                <div class="mb-3">
                                  <label for="exampleInputEmail1" class="form-label">Description</label>
                            <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="description"></textarea>

                                  @error('description')
                                  <span class="text-danger">{{ $message }}</span>
                                  @enderror
                                </div>


                                <div class="mb-3">
                                  <label for="exampleInputEmail1" class="form-label">Slider Image</label>
                                  <input type="file" class="form-control" name="image">
                                  @error('image')
                                  <span class="text-danger">{{ $message }}</span>
                                  @enderror
                                </div>
                                <button type="submit" class="btn btn-primary">Add Slider</button>
                              </form>
                        </div>
                    </div>
                </div>

            </div>
        </div>


    </div>
@endsection

resources/views/admin/slider/edit.blade.php
@extends('admin.admin_master')

@section('admin')

    <div class="py-12">
        <div class="container">
            <div class="row">

                <div class="col-md-8">
                    <div class="card">
                        <div class="card-header">
                            Update Slider
                        </div>
                        <div class="card-body">
                            <form action="{{ route('sliders.update',$sliders->id) }}" method="POST" enctype="multipart/form-data">
                                @csrf
                                @method('PUT')

                                <input type="hidden" name="old_image" value="{{ $sliders->image }}">

                                <div class="mb-3">
                                  <label for="exampleInputEmail1" class="form-label">Title</label>
                                  <input type="text" class="form-control" name="title" value="{{ $sliders->title }}">
                                  @error('title')
                                  <span class="text-danger">{{ $message }}</span>
                                  @enderror
                                </div>

                                <div class="mb-3">
                                  <label for="exampleInputEmail1" class="form-label">Description</label>
                            <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="description">
                                {{ $sliders->description }}
                            </textarea>

                                  @error('description')
                                  <span class="text-danger">{{ $message }}</span>
                                  @enderror
                                </div>


                                <div class="mb-3">
                                  <label for="exampleInputEmail1" class="form-label">Slider Image</label>
                                  <input type="file" class="form-control" name="image" value="{{ $sliders->image }}">
                                  @error('image')
                                  <span class="text-danger">{{ $message }}</span>
                                  @enderror
                                </div>

                                <button type="submit" class="btn btn-primary">Update Slider</button>
                              </form>
                        </div>
                    </div>
                </div>

            </div>
        </div>


    </div>
@endsection

resources/views/admin/slider/index.blade.php
@extends('admin.admin_master')

@section('admin')

    <div class="py-12">
        <div class="container">
            <div class="row">
                <h4>Home Slider</h4>
                <a href="{{ route('sliders.create') }}"> <button class="btn btn-info">Add Slider</button></a>
                <br>
                <br>
                <div class="col-md-12">
                    <div class="card">
                        @if(session('success'))
                            <div class="alert alert-success alert-dismissible fade show" role="alert">
                            <strong>{{ session('success') }}</strong>
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                          </div>
                        @endif
                        <div class="card-header">
                            All Slider
                         </div>
                            <div class="card-body">
                                <table class="table">
                                    <thead>
                                      <tr>
                                        <th scope="col">S No.</th>
                                        <th scope="col">Title</th>
                                        <th scope="col">Image</th>
                                        <th scope="col">Description</th>
                                        <th scope="col">Created At</th>
                                        <th scope="col">Action</th>
                                      </tr>
                                    </thead>
                                    <tbody>
                                        @php ($i = 1)
                                        @foreach ($sliders as $slider)
                                        <tr>
                                            <th scope="row">{{ $i++ }}</th>

                                            <td>{{ $slider->title }}</td>
                                            <td><img src="{{ asset($slider->image) }}" height="40px" width="70px" ></td>
                                            <td>{{ $slider->description }}</td>

                                            <td>
                                                @if ($slider->created_at == NULL)
                                                <span class="text-danger">No Date Set</span>
                                                @else
                                                    {{-- {{ $slider->created_at->diffForHumans()}} --}}
                                                    {{ Carbon\Carbon::parse($slider->created_at)->diffForHumans()}}
                                                    @endif
                                            </td>
                                            <td>
                                                 <a href="{{ route('sliders.show',$slider->id) }}" class="btn btn-warning">Show</a>

                                                 <a href="{{ route('sliders.edit',$slider->id) }}" class="btn btn-info">Edit</a>

                                                <form action="{{ route('sliders.destroy',$slider->id) }}" method="POST">
                                                    @csrf
                                                    @method('DELETE')
                                                <button type="submit" class="btn btn-danger" class="btn-white btn btn-xs">Delete</button>
                                                </form>

                                            </td>
                                        </tr>
                                        @endforeach
                                    </tbody>
                                  </table>
                                  {{ $sliders->links() }}
                            </div>
                    </div>
                </div>

            </div>
        </div>


    </div>
@endsection

resources/views/admin/slider/show.blade.php
@extends('admin.admin_master')

@section('admin')

    <div class="py-12">
        <div class="container">
            <div class="row">

                <div class="col-md-8">
                    <div class="card">
                        <div class="card-header">
                            Add Slider
                        </div>
                        <div class="card-body">
                            <form action="{{ route('sliders.show',$sliders->id) }}" method="POST" enctype="multipart/form-data">
                                @csrf

                                <div class="mb-3">
                                  <label for="exampleInputEmail1" class="form-label">Title</label>
                                  <input type="text" class="form-control" name="title" value="{{ $sliders->title }}">
                                  @error('title')
                                  <span class="text-danger">{{ $message }}</span>
                                  @enderror
                                </div>

                                <div class="mb-3">
                                  <label for="exampleInputEmail1" class="form-label">Description</label>
                            <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="description">
                                {{ $sliders->description }}
                            </textarea>

                                  @error('description')
                                  <span class="text-danger">{{ $message }}</span>
                                  @enderror
                                </div>


                                <div class="mb-3">
                                  <label for="exampleInputEmail1" class="form-label">Slider Image</label>
                                  <input type="file" class="form-control" name="image" value="{{ $sliders->image }}">
                                  @error('image')
                                  <span class="text-danger">{{ $message }}</span>
                                  @enderror
                                </div>
                                {{-- <button type="submit" class="btn btn-primary">Add Slider</button> --}}
                              </form>
                        </div>
                    </div>
                </div>

            </div>
        </div>


    </div>
@endsection